### Import Confusion Matrix

In [1]:
from sklearn.metrics import confusion_matrix

### For the values actual = [0, 1, 0, 1] and predicted = [1, 1, 1, 0]
- Find the confusion matrix.
- Print it out
- Find the values of TN, FP, FN, TP

In [10]:
actual = [0, 1, 0, 1]
predicted = [1, 1, 1, 0]
cm = confusion_matrix(actual, predicted)
print(type(cm))

print(" ", "0", "1", "P")
print("0", "TN", "FP")
print("1", "FN", "TP")
print("A")
print()

print(cm)

<class 'numpy.ndarray'>
  0 1 P
0 TN FP
1 FN TP
A

[[0 2]
 [1 1]]


### For actual = ['B', 'M', 'B', 'M'] and predicted = ['M', 'M', 'M', 'B']
- Find the confusion matrix.
- Print it out
- Find the values of TN, FP, FN, TP

In [9]:
actual = ['B', 'M', 'B', 'M']
predicted = ['M', 'M', 'M', 'B']
cm = confusion_matrix(actual, predicted)

print(" ","0", "1", "Predicted")
print("0","TN", "FP")
print("1","FN", "TP")
print("Actual")
print()

print(cm)

  0 1 Predicted
0 TN FP
1 FN TP
Actual

[[0 2]
 [1 1]]


### For actual = ['W', 'M', 'W', 'M'] and predicted = ['M', 'M', 'M', 'W'] but make W the negative and M the positive

In [8]:
actual = ['W', 'M', 'W', 'M']
predicted = ['M', 'M', 'M', 'W']
cm = confusion_matrix(actual, predicted, labels=["W", "M"])

print(" ","0", "1", "Predicted")
print("0","TN", "FP")
print("1","FN", "TP")
print("Actual")
print()

print("CM", cm)

  0 1 Predicted
0 TN FP
1 FN TP
Actual

CM [[0 2]
 [1 1]]


###  For actual = ["cat", "ant", "cat", "cat", "ant", "bird"] and predicted = ["ant", "ant", "cat", "cat", "ant", "cat"].

In [12]:
actual = ["cat", "ant", "cat", "cat", "ant", "bird"]
predicted = ["ant", "ant", "cat", "cat", "ant", "cat"]
cm = confusion_matrix(actual, predicted, labels=["ant", "cat", "bird"])

print("CM: ", cm)

CM [[2 0 0]
 [1 2 0]
 [0 1 0]]


### The following is actual and predicted values for a cyber-security model.
- actual = ['attack', 'normal', 'normal', 'attack', 'normal', 'normal', 'attack', 'normal', 'attack']
- predicted = ['attack', 'normal', 'attack', 'attack', 'normal', 'normal','normal', 'normal', 'normal']
#### Print out the confusion matrix and the values of tn, fp, fn, tp.

In [17]:
actual = ['attack', 'normal', 'normal', 'attack', 'normal', 'normal', 'attack', 'normal', 'attack']
predicted = ['attack', 'normal', 'attack', 'attack', 'normal', 'normal','normal', 'normal', 'normal']

cm = confusion_matrix(actual, predicted)
r = cm.ravel()
print(type(r))
tn, fp, fn, tp = cm.ravel()
print(f"TN: {tn}, FP: {fp}, FN: {fn}, TP: {tp}")

<class 'numpy.ndarray'>
TN: 2, FP: 2, FN: 1, TP: 4
<class 'numpy.ndarray'>
TN: 4, FP: 1, FN: 2, TP: 2


#### With labels

In [18]:
cm = confusion_matrix(actual, predicted, labels = ["normal", "attack"])
r = cm.ravel()
r = cm.ravel()
print(type(r))
tn, fp, fn, tp = cm.ravel()
print(f"TN: {tn}, FP: {fp}, FN: {fn}, TP: {tp}")

<class 'numpy.ndarray'>
TN: 4, FP: 1, FN: 2, TP: 2
