In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

df = pd.read_csv('data/iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [2]:
# print(df.columns)
print(df.species.value_counts())

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64


In [3]:
# print(df.head())

X = df.drop(['species'], axis='columns')
y = df.species
# print(y)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

clf = KNeighborsClassifier()
clf.fit(X_train, y_train)

print('Accuracy', clf.score(X_test, y_test))

Accuracy 0.9333333333333333


In [5]:
yPredict = clf.predict(X_test)

cm = confusion_matrix(y_test, yPredict, labels=['setosa','versicolor', 'virginica'])
print(cm)

print(np.diag(cm))
print(sum(np.diag(cm))/np.sum(cm))

[[ 8  0  0]
 [ 0  9  2]
 [ 0  0 11]]
[ 8  9 11]
0.9333333333333333
