### 1D ARRAY

In [4]:
import numpy as np
n = np.array([12,3,6,14])
print("n =", n)
print("n.ndim =", n.ndim)
print("n.shape =", n.shape)
print(type(n))
print(n[0])

n = [12  3  6 14]
n.ndim = 1
n.shape = (4,)
<class 'numpy.ndarray'>
12


### 2D ARRAY

In [5]:
n = np.array([ [1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]
               ])
print("n =", n)
print("n.ndim =", n.ndim)
print("n.shape =", n.shape)
print(type(n))
print(n[0,1])

n = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
n.ndim = 2
n.shape = (3, 4)
<class 'numpy.ndarray'>
[1 2 3 4]


### 3D ARRAY

In [7]:
n = np.array(
    [
        [
            [1,2,3,4], [5,6,7,8], [9,10,11,12],
        ],
        [
            [1,2,3,4], [5,6,7,8], [9,10,11,12]
        ],
        [
            [1,2,3,4], [5,6,7,8], [9,10,11,12]
        ]
   ]

)
print("n =", n)
print("n.ndim =", n.ndim)
print("n.shape =", n.shape)
print(type(n))
print(n[0,1])

n = [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
n.ndim = 3
n.shape = (3, 3, 4)
<class 'numpy.ndarray'>
[5 6 7 8]


### Reshape a 1D array to a 2D array

In [10]:
n = np.array([12,3,6,14])
n2 = np.reshape(n,(1,-1))
print(n2)

[[12  3  6 14]]
