#### For the values actual = [0, 1, 0, 1] and predicted = [1, 1, 1, 0]
#### • Find the confusion matrix.
#### • Print it out
#### • Find the values of TN, FP, FN, TP

In [6]:
from sklearn.metrics import confusion_matrix
actual = [0, 1, 0, 1]
predicted = [1, 1, 1, 0]
cm = confusion_matrix(actual, predicted)
print(type(cm))
print(" ","0 ","1 ","P ")
print(0, "TN", "FP")
print(1, "FN", "TP")
print("A")
print()

print("confusion matrix")
print(cm)



<class 'numpy.ndarray'>
  0  1  P 
0 TN FP
1 FN TP
A

confusion matrix
[[0 2]
 [1 1]]


### Do the same for actual = ['B', 'M', 'B', 'M'] and predicted = ['M', 'M', 'M', 'B']

In [7]:
actual = ['B', 'M', 'B', 'M']
predicted = ['M', 'M', 'M', 'B']
cm = confusion_matrix(actual,predicted)
print(type(cm))
print(" ","0 ","1 ","P ")
print(0, "TN", "FP")
print(1, "FN", "TP")
print("A")
print()

print("confusion matrix")
print(cm)

<class 'numpy.ndarray'>
  0  1  P 
0 TN FP
1 FN TP
A

confusion matrix
[[0 2]
 [1 1]]


#### Do the same for actual = ['W', 'M', 'W', 'M'] and predicted = ['M', 'M', 'M', 'W'] but make W
#### the negative and M the positive.

In [8]:
actual = ['W', 'M', 'W', 'M']
predicted = ['M', 'M', 'M', 'W']
# labels forces W to 0(negative) and M to 1(positive)
cm = confusion_matrix(actual, predicted, labels=["W", "M"])
print(type(cm))
print(" ", "0 ", "1 ", "P ")
print(0, "TN", "FP")
print(1, "FN", "TP")
print("A")
print()
print("confusion matrix")
print(cm)

<class 'numpy.ndarray'>
  0  1  P 
0 TN FP
1 FN TP
A

confusion matrix
[[0 2]
 [1 1]]


#### Do the same for actual = ["cat", "ant", "cat", "cat", "ant", "bird"] and predicted = ["ant",
#### "ant", "cat", "cat", "ant", "cat"]

In [9]:
actual = ["cat", "ant", "cat", "cat", "ant", "bird"]
predicted = ["ant","ant", "cat", "cat", "ant", "cat"]
cm = confusion_matrix(actual,predicted)
print(type(cm))
print(cm)
cm = confusion_matrix(actual,predicted, labels = ["ant", "cat", "bird"])
print(type(cm))
print(cm)


<class 'numpy.ndarray'>
[[2 0 0]
 [0 0 1]
 [1 0 2]]
<class 'numpy.ndarray'>
[[2 0 0]
 [1 2 0]
 [0 1 0]]


### The following is actual and predicted values for a cyber-security model.
- actual = ['attack', 'normal', 'normal', 'attack', 'normal', 'normal', 'attack', 'normal', 'attack']
- predicted = ['attack', 'normal', 'attack', 'attack', 'normal', 'normal', 'normal', 'normal', 'normal']
#### Print out the confusion matrix and the values of tn, fp, fn, tp.

In [10]:
actual = ['attack', 'normal', 'normal', 'attack', 'normal', 'normal', 'attack', 'normal', 'attack']
predicted = ['attack', 'normal', 'attack', 'attack', 'normal', 'normal', 'normal', 'normal', 'normal']
cm = confusion_matrix(actual,predicted)
print(type(cm))
print(cm)
r = cm.ravel()
print(type(r))
tn, fp,fn,tp = cm.ravel()
print("TN",tn, "FP",fp, "FN",fn, "TP", tp)

cm = confusion_matrix(actual,predicted, labels =['normal', 'attack'])
print(type(cm))
print(cm)
r = cm.ravel()
print(type(r))
tn, fp,fn,tp = cm.ravel()
print("TN",tn, "FP",fp, "FN",fn, "TP", tp)

<class 'numpy.ndarray'>
[[2 2]
 [1 4]]
<class 'numpy.ndarray'>
TN 2 FP 2 FN 1 TP 4
<class 'numpy.ndarray'>
[[4 1]
 [2 2]]
<class 'numpy.ndarray'>
TN 4 FP 1 FN 2 TP 2
