### Import NumPy

In [ ]:
import numpy as np

In [4]:
x = np.array([12, 3, 6, 14])
print("x: ", x)
print(type(x))
print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)
print(x[0])

x:  [12  3  6 14]
<class 'numpy.ndarray'>
x.ndim:  1
x.shape:  (4,)
12


### 2D Array

In [3]:
x = np.array([  [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]
            ])
print("x: ", x)
print(type(x))
print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)
print(x[0,1])

x:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
x.ndim:  2
x.shape:  (3, 4)
2


### 3D Array

In [6]:
x = np.array([
                [
                    [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]
                ],
                [
                    [21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32]
                ]
            ])
print("x: ", x)
print(type(x))
print("x.ndim: ", x.ndim)
print("x.shape: ", x.shape)

x.ndim:  3
x.shape:  (2, 3, 4)
7


### Array Slice

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(f"{arr[3:8]=}")
print(f"{arr[3:8:2]=}")
print(f"{arr[3:-1]=}")
print(f"{arr[3:]=}")
print(f"{arr[:5]=}")
print(f"{arr[:5]=}")

new = arr[0:3]
print(f"{len(new)=}")
print(f"{new=}")

new[0] = 100
print(f"{new[0]=}")
print(f"{arr[0]=}")
print(f"{arr=}")

arr[3:8]=array([3, 4, 5, 6, 7])
arr[3:8:2]=array([3, 5, 7])
arr[3:-1]=array([3, 4, 5, 6, 7, 8, 9])
arr[3:]=array([ 3,  4,  5,  6,  7,  8,  9, 10])
arr[:5]=array([0, 1, 2, 3, 4])
arr[:5]=array([0, 1, 2, 3, 4])
len(new)=3
new=array([0, 1, 2])
new[0]=np.int64(100)
arr[0]=np.int64(100)
arr=array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])


### Reshape 1D Array to 2D Array

In [10]:
x = np.array([12, 3, 6, 14])
x2 = np.reshape(x, (2,-1))
print(x)
print(x2)
print(x)


[12  3  6 14]
[[12  3]
 [ 6 14]]
[12  3  6 14]
